### ISSUE TITLE
Informationen zum Lied auf Folie anzeigen können

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#100]
Auf der Folie werden die Liederquelle (Liederbuch) und das Copyright angezeigt.
Der Autor kann jedoch nicht angezeigt werden.

Gerne möchte ich noch den Autor anzeigen können. 
Wenn jemandem das LIed gefällt, braucht er den Autor um danach zu suchen. Eine CCLI Nr. kann er sich kaum merken und der Verlag hilft meist auch nicht weiter, wenn es ein grosser ist.

**Comment by rguntli** [comment]
Für mich ist die Umsetzung dieses Issues abgenommen.
