### ISSUE TITLE
Informationen zum Lied Quelle, statt Liederbuch schreiben

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#101]
In den Informationen zum Lied steht Liederbuch, Autor usw..

In den Mastereinstellungen kann jedoch nur Copyright oder Quelle gewählt werden.
Es ist nicht klar, welche Information des Liedes nun angezeigt wird. Liederbuch oder Autor. Die Begriffe müssen vereinheitlicht werden. 
Ideal wäre es, wenn in den Mastereinstellungen gewählt werden könnten, welche Infos von den Liedern angezeigt werden wollen.

Aus meiner Sicht sind die Begriffe Publisher und Verwalter nicht klar. Können auch weggelassen werden.

**Comment by mrcage** [comment]
![grafik](https://user-images.githubusercontent.com/1665428/50530370-0cd80c80-0afd-11e9-819a-2e9f431e8337.png)

**Comment by szeberli** [comment]
sieht gut aus :)

**Comment by rguntli** [comment]
Für mich ist die Umsetzung dieses Issues abgenommen.
