### ISSUE TITLE
Lieder Statistik Zähler

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#102]
Im CCLI muss ich melden, bei wievielen Gottesdiensten/Anlässen das Lied verwendet wurden. Wenn ich das Lied an einem Anlass mehrmals Singe bzw. in die Setliste setzte. wird es mehrmals gezählt.
Beim CCLI müsste ich dies jedoch nur einmal melden.

Somit stimmt diese Statistik für die Gemeinde um zu wissen, wieviel mal haben sie es gesungen. Jedoch nicht für CCLI

**Comment by mrcage** [comment]
Fixed in 70755a4649bb5229c778af5ed2509c3df80d7439

**Comment by rguntli** [comment]
Für mich ist die Umsetzung dieses Issues abgenommen.
