### ISSUE TITLE
Link zum Editor in der Liederstatistik hinzufügen

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#103]
In der Liederstatistik weiss ich zum Teil nicht, was es für ein Lied ist. Deshalb müsste ich es sehen, um es öffnen zu können.
Ideal wäre eine Verknüpfung des Liedernamens. Wenn ich darauf klicke. öffnet sich das Lied im Editor.

**Comment by rguntli** [comment]
Hat funktioniert, wenn ich PBP aus Visual Studio heraus ausgeführt habe.

Hat nicht funktioniert, wenn mit der über den Installer installierten Praisebase Presenter.exe Datei ausgeführt habe. Siehe Fehlermeldung

> Informationen über das Aufrufen von JIT-Debuggen
> anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
> 
> ************** Ausnahmetext **************
> System.IO.FileNotFoundException: Die Datei oder Assembly "MoreLinq, Version=3.1.0.0, Culture=neutral, PublicKeyToken=384d532d7e88985d" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
> Dateiname: "MoreLinq, Version=3.1.0.0, Culture=neutral, PublicKeyToken=384d532d7e88985d"
>    bei PraiseBase.Presenter.Forms.SongStatsticsViewer.PopulateTable(String setlistDir, DateTime startTime, DateTime endTime)
>    bei System.Windows.Forms.DateTimePicker.OnValueChanged(EventArgs eventargs)
>    bei System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
>    bei PraiseBase.Presenter.Forms.SongStatsticsViewer.SongStatsticsViewer_Load(Object sender, EventArgs e)
>    bei System.Windows.Forms.Form.OnLoad(EventArgs e)
>    bei System.Windows.Forms.Form.OnCreateControl()
>    bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    bei System.Windows.Forms.Control.CreateControl()
>    bei System.Windows.Forms.Control.WmShowWindow(Message& m)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.Form.WmShowWindow(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> WRN: Protokollierung der Assemblybindung ist AUS.
> Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.
> Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
> Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.
> 
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> PraiseBase Presenter
>     Assembly-Version: 1.4.1.0.
>     Win32-Version: 1.4.1.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/PraiseBase%20Presenter/PraiseBase%20Presenter.exe.
> ----------------------------------------
> PraiseBase Core Libraries
>     Assembly-Version: 1.4.1.0.
>     Win32-Version: 1.4.1.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/PraiseBase%20Presenter/PraiseBase%20Core%20Libraries.DLL.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3190.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> log4net
>     Assembly-Version: 1.2.13.0.
>     Win32-Version: 1.2.13.0.
>     CodeBase: file:///C:/Program%20Files%20(x86)/PraiseBase%20Presenter/log4net.DLL.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> PresentationCore
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll.
> ----------------------------------------
> WindowsBase
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> PresentationFramework
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll.
> ----------------------------------------
> System.Xaml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll.
> ----------------------------------------
> System.Security
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3101.0 built by: NET472REL1LAST_B.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll.
> ----------------------------------------
> Accessibility
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
> ----------------------------------------
> System.Data
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3160.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
> ----------------------------------------
> System.Data.SqlXml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll.
> ----------------------------------------
> UIAutomationProvider
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll.
> ----------------------------------------
> UIAutomationTypes
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3221.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> WindowsFormsIntegration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll.
> ----------------------------------------
> PresentationFramework.Aero2
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll.
> ----------------------------------------
> 
> ************** JIT-Debuggen **************
> Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
> Konfigurationsdatei der Anwendung oder des Computers
> (machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
> Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.
> 
> Zum Beispiel:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
>

**Comment by mrcage** [comment]
Bitte nochmals testen; eine DLL hat im Installer gefehlt, dies ist nun behoben.

**Comment by rguntli** [comment]
Für mich ist die Umsetzung dieses Issues abgenommen.
