### ISSUE TITLE
Spaltenbreite im Metadaten Editor

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#104]
Die Spalten sind viel zu gross und unübersichtlich.
Möchte ich das Copyright oder die CCLI Lizenz ergänzen verliere ich rasch die Zeile und es passieren Fehler.
Ideal wäre es, wenn man bei jeder Spalte selbst die Grösse Wählen kann. Die Ansicht der Liederstatistik ist viel besser.

Die Spaltenbreite sollte persistent gespeichert werden,
Eine Maximize-Window Button wäre auch noch praktich

**Comment by rguntli** [comment]
Für mich ist die Umsetzung dieses Issues abgenommen.
