### ISSUE TITLE
Youtube ID funktioniert nicht mehr.

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#109]
![grafik](https://user-images.githubusercontent.com/10152825/44845198-323b3380-ac4d-11e8-9c58-00f851e42dc0.png)

**Comment by mrcage** [comment]
Implemented a "cheap" solution by requesting edge-browser compatible behaviour. Needs to be verified if it works with Windows 7.

More eloquent solutions would require adding a lot of libraries (chrome/gecko engine or VLC) and not even then its guaranteed to work. Another solution would require a real edge-browser compatible webcontrol, but this would impose requirement for having Windows 10 to run this software.

**Comment by rguntli** [comment]
Ich habe es mit dem jüngsten .exe native unter Windows 10 ausprobiert.
Nach wie vor erhalte ich die Meldung mit dem Skriptfehler.
Woran könnte das liegen?

**Comment by rguntli** [comment]
Getestet und okay.
