### ISSUE TITLE
small resolution 800x600 / 4:3/ 16:9

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#20]
Hin und wieder muss ich noch mit einem Beamer arbeiten der an meinem Laptop mit 800x600 angefügt wird. Wenn ich diese Einstellung habe, dann wird nur das Hintergrundbild verkleinert und nicht die Schrift. Das heißt: Die Schrift läuft über den Rand hinaus.

**Comment by mrcage** [comment]
This works now. Fixed by bce07c875fff2b81021f9a82cedbb1c2a328cb97
