### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#60]
Chackbox - take over all slides set as default

**Comment by mrcage** [comment]
Bitte genauer erklären :-) Kann da keinen Fehler feststellen

**Comment by szeberli** [comment]
![chackbox auf 1](https://cloud.githubusercontent.com/assets/10152825/6765701/cf6a13e8-cfeb-11e4-8828-e213aaf3898b.PNG)
