### ISSUE TITLE
Asked again if song should be saved

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#7]
**What steps will reproduce the problem?**
1. Create a new song
2. Save the song
3. Close song in the song editor.

**What is the expected output? What do you see instead?**
Song should be closed without asking again if it should be saved.

**What version of the product are you using? On what operating system?**
1.1.2.0 on Windows 7

**Comment by mrcage** [comment]
fixed in 251580894c0bae198b20dc9d359728b81c10ac6d
