### ISSUE TITLE
Recursive creation of [Thumbnails] folder

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#77]
Der [Thumbnails] wird auf der Dropbox von anderen Indexiert.
backgrounds/[Thumbnails]/[Thumbnails]/[Thumbnails]

dieser Ordner [Thumbnails] muss beim indexieren ausgeschlossen werden.

**Comment by szeberli** [comment]
Bei zu vielen Unterordner konnte PB nicht mehr starten.(musste von hand alle unterordner  [Thumbnails] löschen, dann funktoniert es weider. ich denke dieser bug hat priorität :)

**Comment by mrcage** [comment]
Can no longer be reproduced, possibly fixed in older version. Also see  #41

If the bug still occurs with the latest version, please reopen.
