### ISSUE TITLE
Rename a node in the song structure tree

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#8]
What steps will reproduce the problem?
1. Add some nodes in the tree with containing the song structure.
2. Selekt a node to change the label of the node. 
3. Change the label and hit Enter

What is the expected output? What do you see instead?
The new label of the node is not changed.

What version of the product are you using? On what operating system?
1.1.2.0 on Windows 7

Please provide any additional information below.

**Comment by mrcage** [comment]
This issue was fixed with the restyling of the song editor in version 1.2.1.0
