### ISSUE TITLE
Information about Copyrights,.. are lost

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#9]
What steps will reproduce the problem?
1. Add some information about copyrights, author... to a song.
2. Save the song.
3. Reopen the song.

What is the expected output? What do you see instead?
All the additionl information are gone.

What version of the product are you using? On what operating system?
1.1.2.0, Windows 7

Please provide any additional information below.

**Comment by mrcage** [comment]
Not completely fixed, needs some more work (commit message in git should have referenced issue #7)

**Comment by mrcage** [comment]
Futher analysis shows that the issue is indeed fixed ;-)
