### ISSUE TITLE
Verbesserung Copyright

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#97]
**Anzeige Copyright erscheint nicht in Struktur Ansicht**
In der Ansicht Struktur erscheint das Copyright nicht immer. In der Ansicht Ablauf schon. 
Wenn ich im Editor im Ablauf des Liedes die letzte Folie des Liedes nicht auswähle, erscheint das Copyright nicht. (Einstellungen/Masterformatierung/Zusatzinformationen: Copyright anzeigen: auf letzter Folie)
Das Copyright muss jedoch dringend immer angezeigt werden, wenn ich ein Lied projiziere. Es darf nicht in Abhängigkeit von einer Folie sein.

**Comment by rguntli** [comment]
**Das Copyright auf der letzten Folie wird nicht immer angezeigt,** woran liegt das? 
(Input Peter Leuenberger EGW Schönbühl)

**Comment by mrcage** [comment]
Bei mir funktioniert das sowohl in der Ansicht "Struktur" als auch in "Ablauf". Wo es jedoch nicht funktioniert ist, wenn ich eine Setliste verwende; dort habe ich einen Fehler gefunden und werde diesen beheben. Danach bitte nochmals testen.

**Comment by rguntli** [comment]
Ich habe es mit dem jüngsten .exe native unter Windows 10 ausprobiert.
Das erwartete Ergebnis, welches du im vorangehenden Kommentar beschrieben hast, liegt nicht vor.
Woran könnte das liegen? Hast no noch nicht alles gepusht?

**Comment by rguntli** [comment]
Getestet und okay.
