### ISSUE TITLE
Farben des Buttons Struktur und Ablauf verkehrt

### ISSUE THREAD

**Issue by szeberli** [PraiseBase-Presenter/PraiseBase-Presenter#99]
Bei den restlichen Menus und Buttons im Programm ist ein gewählter Button weiss, und ein nicht gewählter hellgrau.

Bei Struktur und Ablauf ist der gewählte Button dunkel grau mit blauem fettem Rand und der nicht gewählte weiss. Dies ist verkehrt und verwirrt beim bedienen.
Der gewählte sollte auch weiss, und der nicht gewählte hellgrau sein.

**Comment by rguntli** [comment]
Für mich ist die Umsetzung dieses Issues abgenommen.
